name: "Go Coverage"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    # Ignore drafts
    if: github.event.pull_request.draft == false
    name: Go test with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 60
          cover-pkg: ./...
          ignore-pattern: |
            /examples/
