name: "Go Testing"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  testing:
    # Ignore drafts
    if: github.event.pull_request.draft == false
    name: Go testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Testing
        run: go test -v ./pkg/...